name: route_planner
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-467.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  equatable:
  flutter_bloc: 8.1.1
  json_annotation: 4.7.0
  freezed_annotation: 2.2.0
  dio: 4.0.6
  dio_http_cache_lts: 0.4.1
  mockito: 5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner:
  freezed:
  json_serializable:
  bloc_test: 9.1.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
